version: '3.8'

services:
  model_auto_switch:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/arm64
        - linux/amd64
    image: model_auto_switch:local
    container_name: model_auto_switch
    restart: always
    ports:
      - "20261:3000"
    volumes:
      - ./runtime:/app/runtime
      - ./app/appconfig/openai_proxy.yaml:/app/app/appconfig/openai_proxy.yaml:ro
    environment:
      - TZ=Asia/Shanghai
      - PORT=3000
